### PR TITLE
Fix https://github.com/Karambirov/GitHubSearch/issues/46

### PR DESCRIPTION
**Pull request by 5SMNOONMS5**

### CODE REVIEW

**Comment by 5SMNOONMS5** [comment]
ok I already delete

**Comment by Karambirov** [comment]
@5SMNOONMS5 Thanks for contributing! 
Have you tested it? Everything's working ok?

**Comment by 5SMNOONMS5** [comment]
of course, i tested it already.

**Comment by 5SMNOONMS5** [comment]
This is my test part. search repo then add it then show up in FavoritesViewController. But another problem is when i click FavoritesViewController tab and then click back SearchViewController tab, Its black. i will check it later again

**Comment by 5SMNOONMS5** [comment]
I will make a new pull request when I fix everything

**Pull request closed without merging**
